# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x05\x61gent\"F\n\x0c\x41gentRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"V\n\x15\x43larificationResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fselected_option\x18\x02 \x01(\t\x12\x10\n\x08\x66reetext\x18\x03 \x01(\t\"+\n\nAgentEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t2\x92\x01\n\x0c\x41gentService\x12\x38\n\x0cProcessQuery\x12\x13.agent.AgentRequest\x1a\x11.agent.AgentEvent0\x01\x12H\n\x13SubmitClarification\x12\x1c.agent.ClarificationResponse\x1a\x11.agent.AgentEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=30
  _globals['_AGENTREQUEST']._serialized_end=100
  _globals['_CLARIFICATIONRESPONSE']._serialized_start=102
  _globals['_CLARIFICATIONRESPONSE']._serialized_end=188
  _globals['_AGENTEVENT']._serialized_start=190
  _globals['_AGENTEVENT']._serialized_end=233
  _globals['_AGENTSERVICE']._serialized_start=236
  _globals['_AGENTSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
