# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'knowledge_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17knowledge_service.proto\x12\tknowledge\"0\n\x10KnowledgeRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"\xae\x01\n\x0fProductDocument\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x17\n\x0fwarranty_months\x18\x05 \x01(\x05\x12\x1a\n\x12manufacturing_date\x18\x06 \x01(\t\x12\x18\n\x10similarity_score\x18\x07 \x01(\x01\"T\n\x11KnowledgeResponse\x12\x11\n\tdocuments\x18\x01 \x03(\t\x12,\n\x08products\x18\x02 \x03(\x0b\x32\x1a.knowledge.ProductDocument2e\n\x10KnowledgeService\x12Q\n\x14RetrieveRelevantDocs\x12\x1b.knowledge.KnowledgeRequest\x1a\x1c.knowledge.KnowledgeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KNOWLEDGEREQUEST']._serialized_start=38
  _globals['_KNOWLEDGEREQUEST']._serialized_end=86
  _globals['_PRODUCTDOCUMENT']._serialized_start=89
  _globals['_PRODUCTDOCUMENT']._serialized_end=263
  _globals['_KNOWLEDGERESPONSE']._serialized_start=265
  _globals['_KNOWLEDGERESPONSE']._serialized_end=349
  _globals['_KNOWLEDGESERVICE']._serialized_start=351
  _globals['_KNOWLEDGESERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
