# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x03llm\"l\n\nLLMRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06memory\x18\x02 \x03(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\"!\n\x0bLLMResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t\"<\n\rIntentRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x1c\n\x14\x63onversation_context\x18\x02 \x03(\t\"\x83\x01\n\x0eIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x65ntities\x18\x03 \x03(\t\x12\x1b\n\x13needs_clarification\x18\x04 \x01(\x08\x12\x1e\n\x16\x63larification_question\x18\x05 \x01(\t\"c\n\x11StructuredRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\")\n\x12StructuredResponse\x12\x13\n\x0bjson_output\x18\x01 \x01(\t2\xc3\x01\n\nLLMService\x12\x33\n\x0eGenerateAnswer\x12\x0f.llm.LLMRequest\x1a\x10.llm.LLMResponse\x12\x39\n\x0e\x43lassifyIntent\x12\x12.llm.IntentRequest\x1a\x13.llm.IntentResponse\x12\x45\n\x12GenerateStructured\x12\x16.llm.StructuredRequest\x1a\x17.llm.StructuredResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=26
  _globals['_LLMREQUEST']._serialized_end=134
  _globals['_LLMRESPONSE']._serialized_start=136
  _globals['_LLMRESPONSE']._serialized_end=169
  _globals['_INTENTREQUEST']._serialized_start=171
  _globals['_INTENTREQUEST']._serialized_end=231
  _globals['_INTENTRESPONSE']._serialized_start=234
  _globals['_INTENTRESPONSE']._serialized_end=365
  _globals['_STRUCTUREDREQUEST']._serialized_start=367
  _globals['_STRUCTUREDREQUEST']._serialized_end=466
  _globals['_STRUCTUREDRESPONSE']._serialized_start=468
  _globals['_STRUCTUREDRESPONSE']._serialized_end=509
  _globals['_LLMSERVICE']._serialized_start=512
  _globals['_LLMSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
