# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crecommendation_service.proto\x12\x0erecommendation\"E\n\x1aStartRecommendationRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"\x83\x01\n\x1d\x46ollowUpRecommendationRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nlast_query\x18\x02 \x01(\t\x12\x15\n\rlast_response\x18\x03 \x01(\t\x12\x0e\n\x06intent\x18\x04 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x05 \x01(\t\"-\n\x16RecommendationResponse\x12\x13\n\x0bsuggestions\x18\x01 \x03(\t2\xfb\x01\n\x15RecommendationService\x12m\n\x17GetStartRecommendations\x12*.recommendation.StartRecommendationRequest\x1a&.recommendation.RecommendationResponse\x12s\n\x1aGetFollowUpRecommendations\x12-.recommendation.FollowUpRecommendationRequest\x1a&.recommendation.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTRECOMMENDATIONREQUEST']._serialized_start=48
  _globals['_STARTRECOMMENDATIONREQUEST']._serialized_end=117
  _globals['_FOLLOWUPRECOMMENDATIONREQUEST']._serialized_start=120
  _globals['_FOLLOWUPRECOMMENDATIONREQUEST']._serialized_end=251
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=253
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=298
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=301
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
