# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tool_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tool_service.proto\x12\x04tool\"\x12\n\x10ListToolsRequest\"M\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x18\n\x10parameter_schema\x18\x03 \x01(\t\"8\n\x11ListToolsResponse\x12#\n\x05tools\x18\x01 \x03(\x0b\x32\x14.tool.ToolDefinition\"O\n\x12\x45xecuteToolRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\"`\n\x13\x45xecuteToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x05\x32\x8f\x01\n\x0bToolService\x12<\n\tListTools\x12\x16.tool.ListToolsRequest\x1a\x17.tool.ListToolsResponse\x12\x42\n\x0b\x45xecuteTool\x12\x18.tool.ExecuteToolRequest\x1a\x19.tool.ExecuteToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTTOOLSREQUEST']._serialized_start=28
  _globals['_LISTTOOLSREQUEST']._serialized_end=46
  _globals['_TOOLDEFINITION']._serialized_start=48
  _globals['_TOOLDEFINITION']._serialized_end=125
  _globals['_LISTTOOLSRESPONSE']._serialized_start=127
  _globals['_LISTTOOLSRESPONSE']._serialized_end=183
  _globals['_EXECUTETOOLREQUEST']._serialized_start=185
  _globals['_EXECUTETOOLREQUEST']._serialized_end=264
  _globals['_EXECUTETOOLRESPONSE']._serialized_start=266
  _globals['_EXECUTETOOLRESPONSE']._serialized_end=362
  _globals['_TOOLSERVICE']._serialized_start=365
  _globals['_TOOLSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
